### PR TITLE
comment out ResetTrimInfoWrapper

### PR DESCRIPTION
**Pull request by ashishgaurav13**
In response to: #6 
Relevant discussion: https://github.com/minerllabs/minerl/pull/121

Tested that PPO/Rainbow/DDDQN were still working.

### CODE REVIEW

**Comment by KarolisRam** [comment]
You could probably also safely remove the wrapper itself from env_wrappers.py and remove the importing of it in the three files you changed.

**Comment by MadcowD** [comment]
@ashishgaurav13  Seconding @KarolisRam  here! Great work :)

**Comment by ashishgaurav13** [comment]
@KarolisRam I wasn't sure if the API would change back again, that's why I just commented it out. If you're sure the API will stay fixed, I can remove the ResetTrimInfoWrapper entirely.

**Comment by MadcowD** [comment]
I'm sure! :D Thank you so much

**Comment by ashishgaurav13** [comment]
Done!

**Comment by MadcowD** [comment]
Thank you!

**Pull request merged**
